/**
 * External ISO Code Systems
 * 
 * ISO 3166-1 alpha-2 country codes and ISO 639-1/639-2 language codes.
 * These are external standards referenced by FHIR but not typically
 * available in FHIR terminology servers.
 * 
 * Sources:
 * - ISO 3166-1: https://www.iso.org/iso-3166-country-codes.html
 * - ISO 639: https://www.loc.gov/standards/iso639-2/php/code_list.php
 * - FHIR References: http://terminology.hl7.org/CodeSystem/languages
 */

import type { CoreCodeSystemMap } from './types';

export const ISO_CODE_SYSTEMS: CoreCodeSystemMap = {
  // ISO 3166-1 alpha-2 Country Codes
  'http://iso.org/iso/3166': [
    { code: 'AD', display: 'Andorra' },
    { code: 'AE', display: 'United Arab Emirates' },
    { code: 'AF', display: 'Afghanistan' },
    { code: 'AG', display: 'Antigua and Barbuda' },
    { code: 'AI', display: 'Anguilla' },
    { code: 'AL', display: 'Albania' },
    { code: 'AM', display: 'Armenia' },
    { code: 'AO', display: 'Angola' },
    { code: 'AQ', display: 'Antarctica' },
    { code: 'AR', display: 'Argentina' },
    { code: 'AS', display: 'American Samoa' },
    { code: 'AT', display: 'Austria' },
    { code: 'AU', display: 'Australia' },
    { code: 'AW', display: 'Aruba' },
    { code: 'AX', display: 'Åland Islands' },
    { code: 'AZ', display: 'Azerbaijan' },
    { code: 'BA', display: 'Bosnia and Herzegovina' },
    { code: 'BB', display: 'Barbados' },
    { code: 'BD', display: 'Bangladesh' },
    { code: 'BE', display: 'Belgium' },
    { code: 'BF', display: 'Burkina Faso' },
    { code: 'BG', display: 'Bulgaria' },
    { code: 'BH', display: 'Bahrain' },
    { code: 'BI', display: 'Burundi' },
    { code: 'BJ', display: 'Benin' },
    { code: 'BL', display: 'Saint Barthélemy' },
    { code: 'BM', display: 'Bermuda' },
    { code: 'BN', display: 'Brunei Darussalam' },
    { code: 'BO', display: 'Bolivia' },
    { code: 'BQ', display: 'Bonaire, Sint Eustatius and Saba' },
    { code: 'BR', display: 'Brazil' },
    { code: 'BS', display: 'Bahamas' },
    { code: 'BT', display: 'Bhutan' },
    { code: 'BV', display: 'Bouvet Island' },
    { code: 'BW', display: 'Botswana' },
    { code: 'BY', display: 'Belarus' },
    { code: 'BZ', display: 'Belize' },
    { code: 'CA', display: 'Canada' },
    { code: 'CC', display: 'Cocos (Keeling) Islands' },
    { code: 'CD', display: 'Congo, Democratic Republic of the' },
    { code: 'CF', display: 'Central African Republic' },
    { code: 'CG', display: 'Congo' },
    { code: 'CH', display: 'Switzerland' },
    { code: 'CI', display: 'Côte d\'Ivoire' },
    { code: 'CK', display: 'Cook Islands' },
    { code: 'CL', display: 'Chile' },
    { code: 'CM', display: 'Cameroon' },
    { code: 'CN', display: 'China' },
    { code: 'CO', display: 'Colombia' },
    { code: 'CR', display: 'Costa Rica' },
    { code: 'CU', display: 'Cuba' },
    { code: 'CV', display: 'Cabo Verde' },
    { code: 'CW', display: 'Curaçao' },
    { code: 'CX', display: 'Christmas Island' },
    { code: 'CY', display: 'Cyprus' },
    { code: 'CZ', display: 'Czech Republic' },
    { code: 'DE', display: 'Germany' },
    { code: 'DJ', display: 'Djibouti' },
    { code: 'DK', display: 'Denmark' },
    { code: 'DM', display: 'Dominica' },
    { code: 'DO', display: 'Dominican Republic' },
    { code: 'DZ', display: 'Algeria' },
    { code: 'EC', display: 'Ecuador' },
    { code: 'EE', display: 'Estonia' },
    { code: 'EG', display: 'Egypt' },
    { code: 'EH', display: 'Western Sahara' },
    { code: 'ER', display: 'Eritrea' },
    { code: 'ES', display: 'Spain' },
    { code: 'ET', display: 'Ethiopia' },
    { code: 'FI', display: 'Finland' },
    { code: 'FJ', display: 'Fiji' },
    { code: 'FK', display: 'Falkland Islands (Malvinas)' },
    { code: 'FM', display: 'Micronesia, Federated States of' },
    { code: 'FO', display: 'Faroe Islands' },
    { code: 'FR', display: 'France' },
    { code: 'GA', display: 'Gabon' },
    { code: 'GB', display: 'United Kingdom' },
    { code: 'GD', display: 'Grenada' },
    { code: 'GE', display: 'Georgia' },
    { code: 'GF', display: 'French Guiana' },
    { code: 'GG', display: 'Guernsey' },
    { code: 'GH', display: 'Ghana' },
    { code: 'GI', display: 'Gibraltar' },
    { code: 'GL', display: 'Greenland' },
    { code: 'GM', display: 'Gambia' },
    { code: 'GN', display: 'Guinea' },
    { code: 'GP', display: 'Guadeloupe' },
    { code: 'GQ', display: 'Equatorial Guinea' },
    { code: 'GR', display: 'Greece' },
    { code: 'GS', display: 'South Georgia and the South Sandwich Islands' },
    { code: 'GT', display: 'Guatemala' },
    { code: 'GU', display: 'Guam' },
    { code: 'GW', display: 'Guinea-Bissau' },
    { code: 'GY', display: 'Guyana' },
    { code: 'HK', display: 'Hong Kong' },
    { code: 'HM', display: 'Heard Island and McDonald Islands' },
    { code: 'HN', display: 'Honduras' },
    { code: 'HR', display: 'Croatia' },
    { code: 'HT', display: 'Haiti' },
    { code: 'HU', display: 'Hungary' },
    { code: 'ID', display: 'Indonesia' },
    { code: 'IE', display: 'Ireland' },
    { code: 'IL', display: 'Israel' },
    { code: 'IM', display: 'Isle of Man' },
    { code: 'IN', display: 'India' },
    { code: 'IO', display: 'British Indian Ocean Territory' },
    { code: 'IQ', display: 'Iraq' },
    { code: 'IR', display: 'Iran' },
    { code: 'IS', display: 'Iceland' },
    { code: 'IT', display: 'Italy' },
    { code: 'JE', display: 'Jersey' },
    { code: 'JM', display: 'Jamaica' },
    { code: 'JO', display: 'Jordan' },
    { code: 'JP', display: 'Japan' },
    { code: 'KE', display: 'Kenya' },
    { code: 'KG', display: 'Kyrgyzstan' },
    { code: 'KH', display: 'Cambodia' },
    { code: 'KI', display: 'Kiribati' },
    { code: 'KM', display: 'Comoros' },
    { code: 'KN', display: 'Saint Kitts and Nevis' },
    { code: 'KP', display: 'Korea, Democratic People\'s Republic of' },
    { code: 'KR', display: 'Korea, Republic of' },
    { code: 'KW', display: 'Kuwait' },
    { code: 'KY', display: 'Cayman Islands' },
    { code: 'KZ', display: 'Kazakhstan' },
    { code: 'LA', display: 'Lao People\'s Democratic Republic' },
    { code: 'LB', display: 'Lebanon' },
    { code: 'LC', display: 'Saint Lucia' },
    { code: 'LI', display: 'Liechtenstein' },
    { code: 'LK', display: 'Sri Lanka' },
    { code: 'LR', display: 'Liberia' },
    { code: 'LS', display: 'Lesotho' },
    { code: 'LT', display: 'Lithuania' },
    { code: 'LU', display: 'Luxembourg' },
    { code: 'LV', display: 'Latvia' },
    { code: 'LY', display: 'Libya' },
    { code: 'MA', display: 'Morocco' },
    { code: 'MC', display: 'Monaco' },
    { code: 'MD', display: 'Moldova' },
    { code: 'ME', display: 'Montenegro' },
    { code: 'MF', display: 'Saint Martin (French part)' },
    { code: 'MG', display: 'Madagascar' },
    { code: 'MH', display: 'Marshall Islands' },
    { code: 'MK', display: 'North Macedonia' },
    { code: 'ML', display: 'Mali' },
    { code: 'MM', display: 'Myanmar' },
    { code: 'MN', display: 'Mongolia' },
    { code: 'MO', display: 'Macao' },
    { code: 'MP', display: 'Northern Mariana Islands' },
    { code: 'MQ', display: 'Martinique' },
    { code: 'MR', display: 'Mauritania' },
    { code: 'MS', display: 'Montserrat' },
    { code: 'MT', display: 'Malta' },
    { code: 'MU', display: 'Mauritius' },
    { code: 'MV', display: 'Maldives' },
    { code: 'MW', display: 'Malawi' },
    { code: 'MX', display: 'Mexico' },
    { code: 'MY', display: 'Malaysia' },
    { code: 'MZ', display: 'Mozambique' },
    { code: 'NA', display: 'Namibia' },
    { code: 'NC', display: 'New Caledonia' },
    { code: 'NE', display: 'Niger' },
    { code: 'NF', display: 'Norfolk Island' },
    { code: 'NG', display: 'Nigeria' },
    { code: 'NI', display: 'Nicaragua' },
    { code: 'NL', display: 'Netherlands' },
    { code: 'NO', display: 'Norway' },
    { code: 'NP', display: 'Nepal' },
    { code: 'NR', display: 'Nauru' },
    { code: 'NU', display: 'Niue' },
    { code: 'NZ', display: 'New Zealand' },
    { code: 'OM', display: 'Oman' },
    { code: 'PA', display: 'Panama' },
    { code: 'PE', display: 'Peru' },
    { code: 'PF', display: 'French Polynesia' },
    { code: 'PG', display: 'Papua New Guinea' },
    { code: 'PH', display: 'Philippines' },
    { code: 'PK', display: 'Pakistan' },
    { code: 'PL', display: 'Poland' },
    { code: 'PM', display: 'Saint Pierre and Miquelon' },
    { code: 'PN', display: 'Pitcairn' },
    { code: 'PR', display: 'Puerto Rico' },
    { code: 'PS', display: 'Palestine, State of' },
    { code: 'PT', display: 'Portugal' },
    { code: 'PW', display: 'Palau' },
    { code: 'PY', display: 'Paraguay' },
    { code: 'QA', display: 'Qatar' },
    { code: 'RE', display: 'Réunion' },
    { code: 'RO', display: 'Romania' },
    { code: 'RS', display: 'Serbia' },
    { code: 'RU', display: 'Russian Federation' },
    { code: 'RW', display: 'Rwanda' },
    { code: 'SA', display: 'Saudi Arabia' },
    { code: 'SB', display: 'Solomon Islands' },
    { code: 'SC', display: 'Seychelles' },
    { code: 'SD', display: 'Sudan' },
    { code: 'SE', display: 'Sweden' },
    { code: 'SG', display: 'Singapore' },
    { code: 'SH', display: 'Saint Helena, Ascension and Tristan da Cunha' },
    { code: 'SI', display: 'Slovenia' },
    { code: 'SJ', display: 'Svalbard and Jan Mayen' },
    { code: 'SK', display: 'Slovakia' },
    { code: 'SL', display: 'Sierra Leone' },
    { code: 'SM', display: 'San Marino' },
    { code: 'SN', display: 'Senegal' },
    { code: 'SO', display: 'Somalia' },
    { code: 'SR', display: 'Suriname' },
    { code: 'SS', display: 'South Sudan' },
    { code: 'ST', display: 'Sao Tome and Principe' },
    { code: 'SV', display: 'El Salvador' },
    { code: 'SX', display: 'Sint Maarten (Dutch part)' },
    { code: 'SY', display: 'Syrian Arab Republic' },
    { code: 'SZ', display: 'Eswatini' },
    { code: 'TC', display: 'Turks and Caicos Islands' },
    { code: 'TD', display: 'Chad' },
    { code: 'TF', display: 'French Southern Territories' },
    { code: 'TG', display: 'Togo' },
    { code: 'TH', display: 'Thailand' },
    { code: 'TJ', display: 'Tajikistan' },
    { code: 'TK', display: 'Tokelau' },
    { code: 'TL', display: 'Timor-Leste' },
    { code: 'TM', display: 'Turkmenistan' },
    { code: 'TN', display: 'Tunisia' },
    { code: 'TO', display: 'Tonga' },
    { code: 'TR', display: 'Turkey' },
    { code: 'TT', display: 'Trinidad and Tobago' },
    { code: 'TV', display: 'Tuvalu' },
    { code: 'TW', display: 'Taiwan' },
    { code: 'TZ', display: 'Tanzania' },
    { code: 'UA', display: 'Ukraine' },
    { code: 'UG', display: 'Uganda' },
    { code: 'UM', display: 'United States Minor Outlying Islands' },
    { code: 'US', display: 'United States' },
    { code: 'UY', display: 'Uruguay' },
    { code: 'UZ', display: 'Uzbekistan' },
    { code: 'VA', display: 'Holy See' },
    { code: 'VC', display: 'Saint Vincent and the Grenadines' },
    { code: 'VE', display: 'Venezuela' },
    { code: 'VG', display: 'Virgin Islands, British' },
    { code: 'VI', display: 'Virgin Islands, U.S.' },
    { code: 'VN', display: 'Viet Nam' },
    { code: 'VU', display: 'Vanuatu' },
    { code: 'WF', display: 'Wallis and Futuna' },
    { code: 'WS', display: 'Samoa' },
    { code: 'YE', display: 'Yemen' },
    { code: 'YT', display: 'Mayotte' },
    { code: 'ZA', display: 'South Africa' },
    { code: 'ZM', display: 'Zambia' },
    { code: 'ZW', display: 'Zimbabwe' },
  ],

  // ISO 639-1/639-2 Language Codes (commonly used in FHIR)
  // http://terminology.hl7.org/CodeSystem/languages
  'http://terminology.hl7.org/CodeSystem/languages': [
    { code: 'aa', display: 'Afar' },
    { code: 'ab', display: 'Abkhazian' },
    { code: 'af', display: 'Afrikaans' },
    { code: 'ak', display: 'Akan' },
    { code: 'sq', display: 'Albanian' },
    { code: 'am', display: 'Amharic' },
    { code: 'ar', display: 'Arabic' },
    { code: 'an', display: 'Aragonese' },
    { code: 'hy', display: 'Armenian' },
    { code: 'as', display: 'Assamese' },
    { code: 'av', display: 'Avaric' },
    { code: 'ae', display: 'Avestan' },
    { code: 'ay', display: 'Aymara' },
    { code: 'az', display: 'Azerbaijani' },
    { code: 'ba', display: 'Bashkir' },
    { code: 'bm', display: 'Bambara' },
    { code: 'eu', display: 'Basque' },
    { code: 'be', display: 'Belarusian' },
    { code: 'bn', display: 'Bengali' },
    { code: 'bh', display: 'Bihari languages' },
    { code: 'bi', display: 'Bislama' },
    { code: 'bo', display: 'Tibetan' },
    { code: 'bs', display: 'Bosnian' },
    { code: 'br', display: 'Breton' },
    { code: 'bg', display: 'Bulgarian' },
    { code: 'my', display: 'Burmese' },
    { code: 'ca', display: 'Catalan' },
    { code: 'cs', display: 'Czech' },
    { code: 'ch', display: 'Chamorro' },
    { code: 'ce', display: 'Chechen' },
    { code: 'zh', display: 'Chinese' },
    { code: 'cu', display: 'Church Slavic' },
    { code: 'cv', display: 'Chuvash' },
    { code: 'kw', display: 'Cornish' },
    { code: 'co', display: 'Corsican' },
    { code: 'cr', display: 'Cree' },
    { code: 'cy', display: 'Welsh' },
    { code: 'da', display: 'Danish' },
    { code: 'de', display: 'German' },
    { code: 'dv', display: 'Divehi' },
    { code: 'nl', display: 'Dutch' },
    { code: 'dz', display: 'Dzongkha' },
    { code: 'el', display: 'Greek' },
    { code: 'en', display: 'English' },
    { code: 'eo', display: 'Esperanto' },
    { code: 'et', display: 'Estonian' },
    { code: 'ee', display: 'Ewe' },
    { code: 'fo', display: 'Faroese' },
    { code: 'fa', display: 'Persian' },
    { code: 'fj', display: 'Fijian' },
    { code: 'fi', display: 'Finnish' },
    { code: 'fr', display: 'French' },
    { code: 'fy', display: 'Western Frisian' },
    { code: 'ff', display: 'Fulah' },
    { code: 'gd', display: 'Gaelic' },
    { code: 'ga', display: 'Irish' },
    { code: 'gl', display: 'Galician' },
    { code: 'gv', display: 'Manx' },
    { code: 'ka', display: 'Georgian' },
    { code: 'gn', display: 'Guarani' },
    { code: 'gu', display: 'Gujarati' },
    { code: 'ht', display: 'Haitian' },
    { code: 'ha', display: 'Hausa' },
    { code: 'he', display: 'Hebrew' },
    { code: 'hz', display: 'Herero' },
    { code: 'hi', display: 'Hindi' },
    { code: 'ho', display: 'Hiri Motu' },
    { code: 'hr', display: 'Croatian' },
    { code: 'hu', display: 'Hungarian' },
    { code: 'ig', display: 'Igbo' },
    { code: 'is', display: 'Icelandic' },
    { code: 'io', display: 'Ido' },
    { code: 'ii', display: 'Sichuan Yi' },
    { code: 'iu', display: 'Inuktitut' },
    { code: 'ie', display: 'Interlingue' },
    { code: 'ia', display: 'Interlingua' },
    { code: 'id', display: 'Indonesian' },
    { code: 'ik', display: 'Inupiaq' },
    { code: 'it', display: 'Italian' },
    { code: 'jv', display: 'Javanese' },
    { code: 'ja', display: 'Japanese' },
    { code: 'kl', display: 'Kalaallisut' },
    { code: 'kn', display: 'Kannada' },
    { code: 'ks', display: 'Kashmiri' },
    { code: 'kr', display: 'Kanuri' },
    { code: 'kk', display: 'Kazakh' },
    { code: 'km', display: 'Central Khmer' },
    { code: 'ki', display: 'Kikuyu' },
    { code: 'rw', display: 'Kinyarwanda' },
    { code: 'ky', display: 'Kirghiz' },
    { code: 'kv', display: 'Komi' },
    { code: 'kg', display: 'Kongo' },
    { code: 'ko', display: 'Korean' },
    { code: 'kj', display: 'Kuanyama' },
    { code: 'ku', display: 'Kurdish' },
    { code: 'lo', display: 'Lao' },
    { code: 'la', display: 'Latin' },
    { code: 'lv', display: 'Latvian' },
    { code: 'li', display: 'Limburgan' },
    { code: 'ln', display: 'Lingala' },
    { code: 'lt', display: 'Lithuanian' },
    { code: 'lb', display: 'Luxembourgish' },
    { code: 'lu', display: 'Luba-Katanga' },
    { code: 'lg', display: 'Ganda' },
    { code: 'mk', display: 'Macedonian' },
    { code: 'mh', display: 'Marshallese' },
    { code: 'ml', display: 'Malayalam' },
    { code: 'mi', display: 'Maori' },
    { code: 'mr', display: 'Marathi' },
    { code: 'ms', display: 'Malay' },
    { code: 'mg', display: 'Malagasy' },
    { code: 'mt', display: 'Maltese' },
    { code: 'mn', display: 'Mongolian' },
    { code: 'na', display: 'Nauru' },
    { code: 'nv', display: 'Navajo' },
    { code: 'nr', display: 'Ndebele, South' },
    { code: 'nd', display: 'Ndebele, North' },
    { code: 'ng', display: 'Ndonga' },
    { code: 'ne', display: 'Nepali' },
    { code: 'nn', display: 'Norwegian Nynorsk' },
    { code: 'nb', display: 'Bokmål, Norwegian' },
    { code: 'no', display: 'Norwegian' },
    { code: 'ny', display: 'Chichewa' },
    { code: 'oc', display: 'Occitan' },
    { code: 'oj', display: 'Ojibwa' },
    { code: 'or', display: 'Oriya' },
    { code: 'om', display: 'Oromo' },
    { code: 'os', display: 'Ossetian' },
    { code: 'pa', display: 'Panjabi' },
    { code: 'pi', display: 'Pali' },
    { code: 'pl', display: 'Polish' },
    { code: 'pt', display: 'Portuguese' },
    { code: 'ps', display: 'Pushto' },
    { code: 'qu', display: 'Quechua' },
    { code: 'rm', display: 'Romansh' },
    { code: 'ro', display: 'Romanian' },
    { code: 'rn', display: 'Rundi' },
    { code: 'ru', display: 'Russian' },
    { code: 'sg', display: 'Sango' },
    { code: 'sa', display: 'Sanskrit' },
    { code: 'si', display: 'Sinhala' },
    { code: 'sk', display: 'Slovak' },
    { code: 'sl', display: 'Slovenian' },
    { code: 'se', display: 'Northern Sami' },
    { code: 'sm', display: 'Samoan' },
    { code: 'sn', display: 'Shona' },
    { code: 'sd', display: 'Sindhi' },
    { code: 'so', display: 'Somali' },
    { code: 'st', display: 'Sotho, Southern' },
    { code: 'es', display: 'Spanish' },
    { code: 'sc', display: 'Sardinian' },
    { code: 'sr', display: 'Serbian' },
    { code: 'ss', display: 'Swati' },
    { code: 'su', display: 'Sundanese' },
    { code: 'sw', display: 'Swahili' },
    { code: 'sv', display: 'Swedish' },
    { code: 'ty', display: 'Tahitian' },
    { code: 'ta', display: 'Tamil' },
    { code: 'tt', display: 'Tatar' },
    { code: 'te', display: 'Telugu' },
    { code: 'tg', display: 'Tajik' },
    { code: 'tl', display: 'Tagalog' },
    { code: 'th', display: 'Thai' },
    { code: 'ti', display: 'Tigrinya' },
    { code: 'to', display: 'Tonga' },
    { code: 'tn', display: 'Tswana' },
    { code: 'ts', display: 'Tsonga' },
    { code: 'tk', display: 'Turkmen' },
    { code: 'tr', display: 'Turkish' },
    { code: 'tw', display: 'Twi' },
    { code: 'ug', display: 'Uighur' },
    { code: 'uk', display: 'Ukrainian' },
    { code: 'ur', display: 'Urdu' },
    { code: 'uz', display: 'Uzbek' },
    { code: 've', display: 'Venda' },
    { code: 'vi', display: 'Vietnamese' },
    { code: 'vo', display: 'Volapük' },
    { code: 'wa', display: 'Walloon' },
    { code: 'wo', display: 'Wolof' },
    { code: 'xh', display: 'Xhosa' },
    { code: 'yi', display: 'Yiddish' },
    { code: 'yo', display: 'Yoruba' },
    { code: 'za', display: 'Zhuang' },
    { code: 'zu', display: 'Zulu' },
  ],
};

